build_and_push_images:
  runs-on: ubuntu-latest
  needs: test_and_lint_backends

  env:
    ACR_NAME: sit722acrweeek7
    ACR_LOGIN_SERVER: sit722acrweeek7.azurecr.io

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  # Azure login using SP JSON
  - name: Azure Login
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  # Explicit Docker login using SP credentials
  - name: Login to ACR with Docker
    run: |
      echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

  # Build and Push Product Service Image
  - name: Build and Push Product Service Image
    run: |
      docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest ./backend/product_service/
      docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest

  # Build and Push Order Service Image
  - name: Build and Push Order Service Image
    run: |
      docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest ./backend/order_service/
      docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

  # Logout from Docker & Azure for security
  - name: Logout from Docker
    run: docker logout ${{ env.ACR_LOGIN_SERVER }}
    if: always()

  - name: Logout from Azure
    run: az logout
    if: always()
